# Generated by Django 5.1.4 on 2025-01-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
        ("product_category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="product_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category",
                to="product_category.productcategorymodel",
            ),
        ),
    ]
