# Generated by Django 5.1.4 on 2025-01-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productmodel_product_category"),
        ("product_customize", "0002_optionmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCustomizationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_customize",
                        to="product_customize.attributemodel",
                    ),
                ),
                (
                    "options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_custom",
                        to="product_customize.optionmodel",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_customize",
                        to="product.productmodel",
                    ),
                ),
            ],
        ),
    ]
