# Generated by Django 5.1.4 on 2025-01-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_customize", "0003_productcustomizationmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionmodel",
            name="attribute",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_text",
                to="product_customize.attributemodel",
            ),
        ),
    ]
