"""
Django settings for e_commerce_backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
# import django

# os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'e_commerce_backend.settings')
# django.setup()



from pathlib import Path
from datetime import timedelta 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure---$s=!bap$$$&=h-r4fes!$(3f_ql(rz@6nq)-8gu$_%yl%7n7"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

CUSTOM_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    
]

# Project related apps

PROJECT_APPS = [
    'user',
    'cart',
    'cart_item',
    'order_items',
    'orders',
    'product_configuration',
    'product_option',
    'product_option_category',
    'product'
    
]


# Django By Default apps 
DJANGO_DEFAULT_APPS = [
    "django.contrib.admin",          # Admin app
    "django.contrib.auth",           # Auth app
    "django.contrib.contenttypes",   # ContentType app
    "django.contrib.sessions",       # Sessions app
    "django.contrib.messages",       # Messages app
    "django.contrib.staticfiles",    # Static files app
]



INSTALLED_APPS = DJANGO_DEFAULT_APPS + PROJECT_APPS + CUSTOM_APPS 



MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "e_commerce_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "e_commerce_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



REST_FRAMEWORK = {
    
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    
    
    # 'DEFAULT_PAGINATION_CLASS': 'Employee.pagination.DynamicPageSizePagination',
     # Default page size if not specified in the request
    #  'PAGE_SIZE': 100, 
    # 'MAX_PAGE_SIZE': 1000,  # Maximum page size to limit abuse
    # "DATETIME_FORMAT": "%Y-%m-%d %I:%M %p",
}

# JWT settings configuration

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),  # Shorter lifetime for security
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # 1 day refresh token lifetime
    "ROTATE_REFRESH_TOKENS": True,  # Enable rotation for better security
    "BLACKLIST_AFTER_ROTATION": True,  # Blacklist old refresh tokens after rotation
    "ALGORITHM": "HS256",  # Standard algorithm
    "AUTH_HEADER_TYPES": ("Bearer",),  # Standard header type
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_USER_CLASS": "user.User",  # Custom user model
}

AUTH_USER_MODEL = 'user.User'